[pack]
name = "mati-qol"
version = "0.1.0"

[enviroment]
minecraft = "1.21.1"
fabric = "0.16.10"

[mods]
appleskin = { version = "3.0.6+mc1.21", side = "both" }
badoptimizations = { version = "2.2.1", side = "client" }
c2me-fabric = { version = "0.3.0+alpha.0.314+1.21.1", side = "server" }
capes = { version = "1.5.4+1.21", side = "client" }
chat-heads = { version = "0.13.11", side = "client" }
ebe = { version = "0.10.2+1.21", side = "client" }
elytra-slot = { version = "9.0.1+1.21.1", side = "both" }
entityculling = { version = "1.7.2", side = "client" }
fabric-api = { version = "0.115.0+1.21.1", side = "both" }
fabric-language-kotlin = { version = "1.13.1+kotlin.2.1.10", side = "both" }
ferrite-core = { version = "7.0.2-hotfix-fabric", side = "both" }
immediatelyfast = { version = "1.3.4+1.21.1-fabric", side = "client" }
iris = { version = "1.8.1+1.21.1-fabric", side = "client" }
krypton = { version = "0.2.8", side = "both" }
lithium = { version = "mc1.21.1-0.14.7-fabric", side = "both" }
modernfix = { version = "5.20.2+mc1.21.1", side = "both" }
modmenu = { version = "11.0.3", side = "client" }
placeholder-api = { version = "2.4.2+1.21", side = "both" }
reeses-sodium-options = { version = "mc1.21.4-1.8.3+fabric", side = "client" }
sodium-dynamic-lights = { version = "fabric-1.21.1-1.0.10", side = "client" }
sodium-extra = { version = "mc1.21.1-0.6.0+fabric", side = "client" }
sodium-extras = { version = "fabric-1.21.1-1.0.7", side = "client" }
sodium-options-api = { version = "fabric-1.21.1-1.0.10", side = "client" }
sodium-options-mod-compat = { version = "fabric-1.21.1-1.0.0", side = "client" }
sodium = { version = "mc1.21.1-0.6.5-fabric", side = "client" }
sodiumleafculling = { version = "1.0.0", side = "client" }
trinkets = { version = "3.10.0", side = "both" }
txnilib = { version = "fabric-1.21.1-1.0.22", side = "both" }
